---
- name: Show information summary
  debug:
    msg: |
      Cloud image: {{ cloud_image_file_name }}
      Cloud version: {{ cloud_image_version }}
      Cloud build: {{ cloud_image_build|default("none") }}
      Vagrant Box file: {{ vagrant_box_file }}
      Vagrant Box version: {{ vagrant_box_version }}

- name: Build Vagrant Box {{ vagrant_box_file }}
  when: build|bool
  include_tasks: build.yaml
