---
vagrant_box_id: "{{ vagrant_box_name }}-{{ arch.name }}"
vagrant_box_file: "{{ vagrant_box_name }}-{{ vagrant_version }}-{{ provider }}-{{ arch.name }}.box"
vagrant_box_path: "{{ build_path }}/{{ vagrant_box_file }}"
vagrant_disk_file: "box.img"
vagrant_disk_format: "qcow2"
vagrant_disk_path: "{{ build_path }}/{{ vagrant_disk_file }}"
vagrant_disk_size_gb: 10
vagrant_disk_size: "{{ vagrant_disk_size_gb }}G"
cloud_image_file: "{{ vagrant_box_id }}.{{ distro.disk_format }}"
cloud_image_path: "{{ build_path }}/{{ cloud_image_file }}"
custom_templates:
- templates/Vagrantfile
- templates/metadata.json
