---
- name: Create Vagrant cloud-init configuration file
  ansible.builtin.template:
    src: "99_vagrant.cfg.j2"
    dest: "{{ build_path }}/99_vagrant.cfg"

- name: Include guestfs tasks
  ansible.builtin.include_tasks: "{{ guestfs }}.yaml"
