---
- name: Create Vagrant init configuration files
  template:
    src: "{{ item }}.j2"
    dest: "{{ build_path }}/{{ item }}"
  loop:
  - '99_vagrant.cfg'
  - 'config.ign'

- include_tasks: "{{ guestfs }}.yaml"
