---
- name: Create build directory
  file:
    path: "{{ build_path }}"
    state: directory
    mode: '0755'

- name: Create template vars
  copy:
    content: |
      ---
      distro_build: "{{ release.build|default(distro.build|default('0.0.0')) }}"
      base_url: "{{ release.base_url|default(distro.base_url|default(None)) }}"
      file_url: "{{ release.file_url|default(distro.file_url|default(None)) }}"
      checksum: "{{ release.checksum|default(distro.checksum|default(None)) }}"
    dest: "{{ build_path }}/distro.yaml"
  changed_when: false

- name: Load templated vars
  include_vars: "{{ build_path }}/distro.yaml"

- name: Remove template vars
  file:
    path: "{{ build_path }}/distro.yaml"
    state: absent
  changed_when: false

- name: Set build version from URL
  when: distro_build == '0.0.0'
  block:
  - name: Identify latest build
    shell: |
      curl -fsSL {{ base_url }} | \
      pup {{ distro.pup_filter }} | \
      awk {{ distro.awk_filter }} | \
      sort --unique -V | \
      tail -1
    changed_when: false
    register: latest_build
    retries: 5
    until: latest_build.stdout != ""

  - name: Identify latest build version
    set_fact:
      build_version: "{{ ((latest_build.stdout|replace('-','.')+'.0.0')|split('.'))[:3]|join('.') }}"
      build: "{{ latest_build.stdout }}"

- name: Set build version from YAML
  when: distro_build != '0.0.0'
  set_fact:
    build_version: "{{ distro_build }}"

- name: Check for providers
  include_tasks: box.yaml
  vars:
    archs: "{{ box_info.json.versions|selectattr('number', 'eq', build_version)|map(attribute='providers')|first|default([])|selectattr('name', 'eq', provider)|map(attribute='architecture') }}"
  loop: "{{ providers }}"
  loop_control:
    loop_var: provider
  when: arch.name not in archs
