---
- hosts: localhost
  connection: local
  gather_facts: true
  tasks:
  - name: Prechecks
    ansible.builtin.include_tasks: prechecks.yaml

  - name: Load distros data
    ansible.builtin.include_vars: "../distros.yaml"

  - name: Filter distros data
    ansible.builtin.include_tasks: filter.yaml

  - name: Refresh VAGRANT_CLOUD_TOKEN
    ansible.builtin.include_tasks: hcp.yaml

  - name: Include distro tasks
    ansible.builtin.include_tasks: distro.yaml
    loop: "{{ distros }}"
    loop_control:
      loop_var: distro
