---
- hosts: localhost
  connection: local
  gather_facts: true
  tasks:
  - name: Create build directory
    file:
      path: "{{ build_path }}"
      state: directory
      mode: '0755'

  - include_vars: "../distros.yaml"

  - include_tasks: hcp.yaml
    when: vagrant_cloud_token is undefined

  - include_tasks: distro.yaml
    loop: "{{ distros }}"
    loop_control:
      loop_var: distro

  - name: Remove build directory
    when: not dryrun
    file:
      path: "{{ build_path }}"
      state: absent
