---
- name: Create template vars
  copy:
    content: |
      ---
      cloud_image_build: {{ release.cloud_image_build|default(distro.cloud_image_build|default('null')) }}
      cloud_image_base_url: "{{ release.cloud_image_base_url|default(distro.cloud_image_base_url|default(None)) }}"
      cloud_image_url: "{{ release.cloud_image_url|default(distro.cloud_image_url|default(None)) }}"
      cloud_image_checksum: "{{ release.cloud_image_checksum|default(distro.cloud_image_checksum|default(None)) }}"
    dest: "{{ build_path }}/distro.yaml"
  changed_when: false

- name: Load templated vars
  include_vars: "{{ build_path }}/distro.yaml"

- name: Set build version from URL
  block:
  - name: Identify latest build
    shell: |
      curl --max-time 5 --retry 3 -fsSL {{ cloud_image_base_url }} | \
      pup {{ distro.pup_filter }} | \
      awk {{ distro.awk_filter }} | \
      sort --unique -V | \
      tail -1
    changed_when: false
    register: last_build
    retries: 3
    until: last_build.stdout != ""

  - name: Set build version
    set_fact:
      cloud_image_build: "{{ last_build.stdout }}"

- name: Set Vagrant version
  set_fact:
    vagrant_version: "{{ ((cloud_image_build|replace('-','.')+'.0.0')|split('.'))[:3]|join('.') }}"

- name: Refresh VAGRANT_CLOUD_TOKEN
  include_tasks: hcp.yaml

- name: Create Vagrant Box Registry version {{ vagrant_version }}
  when: not dryrun
  uri:
    url: "{{ vagrant_cloud_url }}/registry/{{ vagrant_cloud_user }}/box/{{ vagrant_box_name }}/versions"
    method: POST
    body_format: json
    status_code: [200, 409]
    headers:
      Content-Type: application/json
      Authorization: "Bearer {{ vagrant_cloud_token }}"
    body:
      name: "{{ vagrant_version }}"
  register: hcp_create_version
  changed_when: hcp_create_version.status == 200

- include_role:
    name: "{{ provider }}"

- name: Refresh VAGRANT_CLOUD_TOKEN
  include_tasks: hcp.yaml

- name: Release Vagrant box version {{ vagrant_version }}
  when: not dryrun
  uri:
    url: "{{ vagrant_cloud_url }}/registry/{{ vagrant_cloud_user }}/box/{{ vagrant_box_name }}/version/{{ vagrant_version }}/release"
    method: PUT
    status_code: [200, 400]
    headers:
      Content-Type: application/json
      Authorization: "Bearer {{ vagrant_cloud_token }}"
  register: hcp_release_version
  changed_when: hcp_release_version.status == 200

- name: Delete templete vars
  file:
    path: "{{ build_path }}/distro.yaml"
    state: absent
