---
- name: Create template vars
  copy:
    content: |
      ---
      cloud_image_base_url: "{{ release.cloud_image_base_url|default(distro.cloud_image_base_url) }}"
      cloud_image_file_name: "{{ release.cloud_image_file_name|default(distro.cloud_image_file_name) }}"
      cloud_image_url: "{{ release.cloud_image_url|default(distro.cloud_image_url) }}"
      cloud_image_checksum_type: "{{ release.cloud_image_checksum_type|default(distro.cloud_image_checksum_type|default(None)) }}"
      cloud_image_checksum_url: "{{ release.cloud_image_checksum_url|default(distro.cloud_image_checksum_url|default(None)) }}"
      pup_filter: "{{ (release.pup_filter|default(distro.pup_filter))|shell_escape() }}"
      awk_filter: "{{ (release.awk_filter|default(distro.awk_filter))|shell_escape() }}"
    dest: "{{ build_path }}/distro.yaml"
  changed_when: false

- name: Load templated vars
  include_vars: "{{ build_path }}/distro.yaml"

- name: Identify latest version/build
  shell: |
    curl --max-time 5 --retry 3 -fsSL {{ cloud_image_base_url }} | \
    pup {{ pup_filter }} | \
    awk {{ awk_filter }} | \
    sort --unique -V | \
    tail -1
  changed_when: false
  register: last_build
  retries: 5
  delay: 10
  until: last_build.stdout != ''
  ignore_errors: true

- include_tasks: build.yaml
  when: last_build is success
