---
- name: Create template vars
  copy:
    content: |
      ---
      cloud_image_base_url: "{{ release.cloud_image_base_url|default(distro.cloud_image_base_url) }}"
      cloud_image_file_name: "{{ release.cloud_image_file_name|default(distro.cloud_image_file_name) }}"
      cloud_image_url: "{{ release.cloud_image_url|default(distro.cloud_image_url) }}"
      cloud_image_checksum_type: "{{ release.cloud_image_checksum_type|default(distro.cloud_image_checksum_type|default(None)) }}"
      cloud_image_checksum_url: "{{ release.cloud_image_checksum_url|default(distro.cloud_image_checksum_url|default(None)) }}"
      cloud_image_version_filter: "{{ (release.cloud_image_version_filter|default(distro.cloud_image_version_filter)) }}"
      cloud_image_version_pattern: "{{ (release.cloud_image_version_pattern|default(distro.cloud_image_version_pattern)) }}"
    dest: "{{ build_path }}/distro.yaml"
  changed_when: false

- name: Load templated vars
  include_vars: "{{ build_path }}/distro.yaml"

- name: Get latest version
  set_fact:
    cloud_last_version: "{{ cloud_image_base_url|get_latest_version(cloud_image_version_filter) }}"

- name: Get version values
  set_fact:
    cloud_image_version: "{{ cloud_last_version.version|default(None) if cloud_last_version.version is defined else None}}"
    cloud_image_major: "{{ cloud_last_version.major|default(None) if cloud_last_version.major is defined else None}}"
    cloud_image_minor: "{{ cloud_last_version.minor|default(None) if cloud_last_version.minor is defined else None}}"
    cloud_image_patch: "{{ cloud_last_version.patch|default(None) if cloud_last_version.patch is defined else None}}"
    cloud_image_build: "{{ cloud_last_version.build|default(None) if cloud_last_version.build is defined else None}}"

- name: Set Vagrant Box version
  set_fact:
    vagrant_box_version: "{{ cloud_image_version_pattern|semantic_version(major_version, minor_version, patch_version, build_version) }}"

- include_tasks: build.yaml
