name: Testing

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - id: hcp_auth
      uses: hashicorp/hcp-auth-action@v0
      with:
        workload_identity_provider: 'iam/project/cdb1b80e-a7cd-4d5c-a9a2-3a93079d6a36/service-principal/github/workload-identity-provider/github-vagrant-cloud-images'
        set_access_token: true
    - uses: hashicorp/hcp-setup-action@v0
      with:
        version: 'latest'
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        cache: false
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libguestfs-tools qemu-utils
        go install github.com/ericchiang/pup@latest
    - name: Build images
      env:
        VAGRANT_CLOUD_TOKEN: ${{ steps.hcp_auth.outputs.access_token }}
      run: |
        ansible-playbook -e dryrun=true -e guestfs=guestmount ansible/site.yaml -vvv
