name: Testing

on:
  push:

env:
  VAGRANT_CLOUD_USER: ${{ vars.VAGRANT_CLOUD_USER }}
  VAGRANT_CLOUD_TOKEN: ${{ secrets.VAGRANT_CLOUD_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
    - name: Install dependencies
      run: |
        go install github.com/ericchiang/pup@latest
    - name: Build images
      run: ansible-playbook -e dryrun=true ansible/site.yaml -vvv
